---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
  name: efs-csi-controller-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::613036180535:role/AmazonEKS_EFS_CSI_DriverRole

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: efs-csi-controller-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: efs-csi-controller-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: default
