pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                script {
                    echo("building image")
                }
            }
        }

        stage('push image') {
            steps {
                script {
                    echo("pushing image")
                }
            }
        }

        stage('deploy kubernetes') {
            environment {
                tag_version = "${env.BUILD_ID}"
            }
            steps {
                script {
                    echo("deploy stage")
                }
            }
        }
    }
}