---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:647614927793:certificate/919141c6-3ecd-46a5-9465-3aeece92eab7
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    app: api
    tier: backend
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
