---
apiVersion: v1
kind: Service
metadata:
  name: apps-a
  labels:
    tier: frontend
spec:
  selector:
    app: app-a
    tier: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32001

---
apiVersion: v1
kind: Service
metadata:
  name: apps-b
  labels:
    tier: frontend
spec:
  selector:
    app: app-b
    tier: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32002

---
apiVersion: v1
kind: Service
metadata:
  name: apps-c
  labels:
    tier: frontend
spec:
  selector:
    app: app-c
    tier: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32003

---
apiVersion: v1
kind: Service
metadata:
  name: apps-d
  labels:
    tier: frontend
spec:
  selector:
    app: app-d
    tier: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32004
