---
apiVersion: v1
kind: Service
metadata:
  name: apps-a
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:647614927793:certificate/919141c6-3ecd-46a5-9465-3aeece92eab7
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"

  labels:
    tier: frontend
spec:
  selector:
    app: app-a
    tier: frontend
  type: NodePort
  ports:
    - port: 443
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apps-b
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:647614927793:certificate/919141c6-3ecd-46a5-9465-3aeece92eab7
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    tier: frontend
spec:
  selector:
    app: app-b
    tier: frontend
  type: NodePort
  ports:
    - port: 443
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apps-c
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:647614927793:certificate/919141c6-3ecd-46a5-9465-3aeece92eab7
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    tier: frontend
spec:
  selector:
    app: app-c
    tier: frontend
  type: NodePort
  ports:
    - port: 443
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apps-d
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:647614927793:certificate/919141c6-3ecd-46a5-9465-3aeece92eab7
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    tier: frontend
spec:
  selector:
    app: app-d
    tier: frontend
  type: NodePort
  ports:
    - port: 443
      targetPort: 80
